const EmuStat = [
  {
    id: 'FirmwareVersionModule',
    register: 4108,
    unit: '',
    label: 'Firmware Version Modul ',
  },
  {
    id: 'SerialNumber',
    register: 4109,
    unit: '',
    label: 'Seriennummer Zähler',
  },
  {
    id: 'SoftwareVersion',
    register: 4111,
    unit: '',
    label: 'Software Version und Checksumme',
  },
  {
    id: 'SystemTime',
    register: 4200,
    unit: '',
    label: 'Momentane Systemzeit',
  },
  {
    id: 'WirkEnergieBezugTotal',
    register: 4202,
    unit: 'Wh',
    label: 'Wirk- Energie Bezug Tota',
  },
  {
    id: 'WirkEnergieBezugTotalTarif1',
    register: 4230,
    unit: 'Wh',
    label: 'Wirk- Energie Bezug Total Tarif 1',
  },
  {
    id: 'WirkEnergieBezugTotalTarif2',
    register: 4246,
    unit: 'Wh',
    label: 'Wirk- Energie Bezug Total Tarif 2',
  },
  {
    id: 'WirkEnergieLieferungTotalLieferung',
    register: 4282,
    unit: 'Wh',
    label: 'Wirk- Energie Lieferung Total Lieferung',
  },
  {
    id: 'WirkEnergieLieferungTotalTarif1',
    register: 4310,
    unit: 'Wh',
    label: 'Wirk- Energie Lieferung Total Tarif 1',
  },
  {
    id: 'WirkEnergieLieferungTotalTarif2',
    register: 4326,
    unit: 'Wh',
    label: 'Wirk- Energie Lieferung Total Tarif 2',
  },
  {
    id: 'AktuelleWiekLeistungPhaseL1',
    register: 4522,
    unit: 'W',
    label: 'Aktuelle Wirk- Leistung Phase L1',
  },
  {
    id: 'AktuelleWiekLeistungPhaseL2',
    register: 4524,
    unit: 'W',
    label: 'Aktuelle Wirk- Leistung Phase L2',
  },
  {
    id: 'AktuelleWiekLeistungPhaseL3',
    register: 4526,
    unit: 'W',
    label: 'Aktuelle Wirk- Leistung Phase L3',
  },
  {
    id: 'AktuelleWirkLeistungTotal',
    register: 4528,
    unit: 'W',
    label: 'Aktuelle Wirk- Leistung Total',
  },
  {
    id: 'AktuelleSpannungPhaseL1',
    register: 4568,
    unit: 'V/10',
    label: 'Aktuelle Spannung Phase L1',
  },
  {
    id: 'AktuelleSpannungPhaseL2',
    register: 4569,
    unit: 'V/10',
    label: 'Aktuelle Spannung Phase L2',
  },
  {
    id: 'AktuelleSpannungPhaseL3',
    register: 4570,
    unit: 'V/10',
    label: 'Aktuelle Spannung Phase L3',
  },
  {
    id: 'AktuelleSpannungPhaseL1L2',
    register: 4571,
    unit: 'V/10',
    label: 'Aktuelle Spannung Phase L1 – L2',
  },
  {
    id: 'AktuelleSpannungPhaseL2L3',
    register: 4572,
    unit: 'V/10',
    label: 'Aktuelle Spannung Phase L2 – L3',
  },
  {
    id: 'AktuelleSpannungPhaseL3L1',
    register: 4573,
    unit: 'V/10',
    label: 'Aktuelle Spannung Phase L3 – L1',
  },
  {
    id: 'AktuellerStromPhaseL1',
    register: 4592,
    unit: 'mA',
    label: 'Aktueller Strom Phase L1',
  },
  {
    id: 'AktuellerStromPhaseL2',
    register: 4594,
    unit: 'mA',
    label: 'Aktueller Strom Phase L2',
  },
  {
    id: 'AktuellerStromPhaseL13',
    register: 4596,
    unit: 'mA',
    label: 'Aktueller Strom Phase L3',
  },
  {
    id: 'AktuellerStromTotal',
    register: 4598,
    unit: 'mA',
    label: 'Aktueller Strom Total ',
  },
  {
    id: 'AktuellerFormfaktorPhaseL1',
    register: 4624,
    unit: 'Cos/100',
    label: 'Aktueller Formfaktor Phase L1 (cos phi)',
  },
  {
    id: 'AktuellerFormfaktorPhaseL2',
    register: 4625,
    unit: 'Cos/100',
    label: 'Aktueller Formfaktor Phase L2 (cos phi)',
  },
  {
    id: 'AktuellerFormfaktorPhaseL3',
    register: 4626,
    unit: 'Cos/100',
    label: 'Aktueller Formfaktor Phase L3 (cos phi)',
  },
  {
    id: 'AktuelleNetzfrequenz',
    register: 4627,
    unit: 'Hz/10',
    label: 'Aktuelle Netzfrequenz',
  },
  {
    id: 'AnzahlSpannungsausfaelle',
    register: 4628,
    unit: '',
    label: 'Anzahl Spannungsausfälle am Zähler',
  },
  {
    id: 'MomentanAktuellerTarif',
    register: 4630,
    unit: 'W',
    label: 'Momentan aktueller Tarif',
  },
]

export default EmuStat
